### ISSUE TITLE
Unable to view Codespaces

### ISSUE THREAD

**Issue by zeropointnothing** [Shock-Awesum4961/RapidReact#2]
I'm doing this here just in case nobody notices the Pull Request (It became that since I don't have write permissions)

I am unable to view the Codespace. However, this simply could just be a permissions issue or because I don't have Write Access to the repo.

**Comment by zeropointnothing** [comment]
@aaron-frc4961 that should be able to give you a notification. dont know why i didn't do that the first time

**Comment by aaron-frc4961** [comment]
@ZeroPointNothing I'll look into a "format" then

**Comment by zeropointnothing** [comment]
Alrighty.
